# Generated by Django 4.2.7 on 2025-10-06 12:14

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('admin', '관리자'), ('customs', '관세사')], default='customs', max_length=10)),
                ('customs_code', models.CharField(blank=True, max_length=5, null=True, unique=True, verbose_name='관세사부호')),
                ('customs_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='관세사명')),
                ('is_first_login', models.BooleanField(default=True, verbose_name='최초 로그인 여부')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='신고서명')),
                ('declaration_type', models.CharField(choices=[('export', '수출신고서'), ('import', '수입신고서'), ('correction', '수출정정')], max_length=20, verbose_name='신고서 유형')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '신고서',
                'verbose_name_plural': '신고서',
                'db_table': 'declarations',
                'ordering': ['service', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='서비스명')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('db_host', models.CharField(blank=True, max_length=255, null=True, verbose_name='DB 호스트')),
                ('db_port', models.CharField(blank=True, max_length=10, null=True, verbose_name='DB 포트')),
                ('db_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='DB 이름')),
                ('db_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='DB 사용자')),
                ('db_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='DB 비밀번호')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '서비스',
                'verbose_name_plural': '서비스',
                'db_table': 'services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, verbose_name='기본 설정 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_users', to='core.service', verbose_name='서비스')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_users', to=settings.AUTH_USER_MODEL, verbose_name='관세사')),
            ],
            options={
                'verbose_name': '서비스 사용자',
                'verbose_name_plural': '서비스 사용자',
                'db_table': 'service_users',
                'unique_together': {('service', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MappingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unipass_field_name', models.CharField(max_length=200, verbose_name='유니패스 항목명')),
                ('db_table_name', models.CharField(max_length=100, verbose_name='DB 테이블명')),
                ('db_field_name', models.CharField(max_length=100, verbose_name='DB 필드명')),
                ('field_type', models.CharField(choices=[('string', '문자열'), ('number', '숫자'), ('date', '날짜'), ('datetime', '날짜시간'), ('boolean', '참/거짓')], default='string', max_length=20, verbose_name='필드 타입')),
                ('field_length', models.IntegerField(blank=True, null=True, verbose_name='필드 길이')),
                ('priority', models.IntegerField(default=0, verbose_name='우선순위')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='core.declaration', verbose_name='신고서')),
                ('service_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='core.serviceuser', verbose_name='서비스 사용자')),
            ],
            options={
                'verbose_name': '매핑정보',
                'verbose_name_plural': '매핑정보',
                'db_table': 'mapping_info',
                'ordering': ['declaration', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceProcessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='invoices/%Y/%m/%d/', verbose_name='인보이스 이미지')),
                ('ocr_text', models.TextField(blank=True, null=True, verbose_name='OCR 추출 텍스트')),
                ('gpt_request', models.TextField(blank=True, null=True, verbose_name='GPT 요청')),
                ('gpt_response', models.TextField(blank=True, null=True, verbose_name='GPT 응답')),
                ('result_json', models.JSONField(blank=True, null=True, verbose_name='결과 JSON')),
                ('status', models.CharField(choices=[('pending', '처리 대기'), ('processing', '처리 중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20, verbose_name='처리 상태')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='에러 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일시')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='처리 시간')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_logs', to='core.declaration', verbose_name='신고서')),
                ('service_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_logs', to='core.serviceuser', verbose_name='서비스 사용자')),
            ],
            options={
                'verbose_name': '인보이스 처리 로그',
                'verbose_name_plural': '인보이스 처리 로그',
                'db_table': 'invoice_process_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='declaration',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='core.service', verbose_name='서비스'),
        ),
        migrations.CreateModel(
            name='PromptConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(choices=[('basic', '기본 입력항목'), ('additional', '추가 입력항목')], max_length=20, verbose_name='프롬프트 유형')),
                ('prompt_text', models.TextField(verbose_name='프롬프트 내용')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prompts', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='core.mappinginfo', verbose_name='매핑정보')),
                ('service_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='core.serviceuser', verbose_name='서비스 사용자')),
            ],
            options={
                'verbose_name': '프롬프트 설정',
                'verbose_name_plural': '프롬프트 설정',
                'db_table': 'prompt_configs',
                'unique_together': {('mapping', 'prompt_type', 'service_user')},
            },
        ),
    ]
