# Generated by Django 4.2.7 on 2025-10-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='specification_file',
            field=models.FileField(blank=True, null=True, upload_to='specifications/%Y/%m/', verbose_name='항목정의서'),
        ),
    ]
